# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
platform :ios, '7.0'
pod 'AFNetworking', '~> 3.0'

target 'Earthquake' do

end

target 'EarthquakeTests' do

end

target 'EarthquakeUITests' do

end

